on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install gdown
        run: python -m pip install gdown

      - name: Download JDK from Google Drive
        run: gdown --id 1lLp5lbEcBYa1xUkzHJnOrgZW-8MIoRms -O jdk-23_windows-x64_bin.msi

      - name: Install JDK
        run: |
          Start-Process -FilePath "jdk-23_windows-x64_bin.msi" -ArgumentList "/quiet /norestart" -Wait
        shell: pwsh

      - name: Verify Java Installation
        run: java -version
        
      - name: Regenerate Maven Wrapper
        run: mvn -N io.takari:maven:wrapper
        
      - name: Set up Maven Wrapper
        run: chmod +x ./mvnw
        shell: bash

      - name: Build Project with Maven
        run: ./mvnw clean verify -Pprod,war -X
        shell: bash

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: artifact
          path: .
          if-no-files-found: warn
          retention-days: 30
          compression-level: 6
          overwrite: false
          include-hidden-files: false
