name: Run Self-Hosted Runner

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  run-selfhosted-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: oc-2/app
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run self-hosted runner
        run: cd actions-runner && ./run.sh
